version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: unifalmg
      POSTGRES_PASSWORD: unifalmg123
      POSTGRES_DB: escola
    ports:
      - "5432:5432"  
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
